# docker/nginx/default.conf

# Reindirizza tutto il traffico da HTTP a HTTPS
server {
    listen 80;
    server_name gandomullac.dev;
    return 301 https://$server_name$request_uri;
}

# Blocco principale del server per HTTPS
server {
    listen 443 ssl;
    server_name gandomullac.dev;

    # Percorsi dei certificati DENTRO il container
    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # --- MODIFICA QUI ---
    # Imposta la root alla directory 'public'
    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        # Questa direttiva ora userà correttamente /var/www/html/public come $document_root
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
